# Generated by Django 5.2.4 on 2025-08-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='codigo_pulseira',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ingresso',
            name='cpf',
            field=models.CharField(default=12345678910, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresso',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ingresso',
            name='id_cobranca',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ingresso',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
