# Generated by Django 5.2.4 on 2025-08-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0002_ingresso_codigo_pulseira_ingresso_cpf_ingresso_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresso',
            name='codigo_qr',
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='nome_cliente',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
