# Generated by Django 5.2.4 on 2025-08-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0003_remove_ingresso_codigo_qr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='nome_cliente',
            field=models.CharField(max_length=100),
        ),
    ]
