# Generated by Django 5.2.4 on 2025-08-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingressos', '0004_alter_ingresso_cpf_alter_ingresso_nome_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.IntegerField(help_text='Preço em centavos')),
                ('imagem', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cobranca', models.CharField(max_length=100, unique=True)),
                ('status_pagamento', models.CharField(default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingressos.ingresso')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.produto')),
            ],
        ),
    ]
