# Generated by Django 5.2.4 on 2025-07-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pulseira_id', models.CharField(max_length=100, unique=True)),
                ('tipo_ingresso', models.CharField(choices=[('pista', 'Pista'), ('camarote', 'Camarote')], max_length=10)),
                ('pagamento_confirmado', models.BooleanField(default=False)),
                ('data_chegada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
