# Generated by Django 5.2.4 on 2025-08-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_ingresso',
            field=models.CharField(choices=[('pista', 'Pista'), ('vip', 'Vip')], max_length=10),
        ),
    ]
